### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by kyranjamie** [unsafecode/ng2-aot#1] opened 2017-01-18 13:32 UTC
Tried to give this a run.  Something todo with missing `genDir`?  Issue for reference.

```
node -v
v6.1.0
```

Build command:

```
Hash: 99b9b2ec88050d744e51
Version: webpack 2.1.0-beta.22
Time: 1472ms
         Asset    Size  Chunks             Chunk Names
main.bundle.js  859 kB       0  [emitted]  main
    + 175 hidden modules

ERROR in Cannot read property 'codeGen' of undefined

ERROR in ./app/main.jit.ts
Module not found: Error: Can't resolve './../$$_gendir/app/app.module.ngfactory' in '/Users/kyran/dev/demo/ng2-aot/app'
 @ ./app/main.jit.ts 2:0-77

ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
Module not found: Error: Can't resolve '/Users/kyran/dev/demo/ng2-aot/$$_gendir' in '/Users/kyran/dev/demo/ng2-aot/node_modules/@angular/core/src/linker'
 @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 46:15-36 58:15-102
 @ ./~/@angular/core/src/linker.js
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./~/@angular/platform-browser/src/browser.js
 @ ./~/@angular/platform-browser/src/platform-browser.js
 @ ./~/@angular/platform-browser/index.js
 @ ./app/main.jit.ts
```

**Comment by alexmontdor** [comment] 2017-01-25 18:50
Hi

I find out that if you are using version 1.1.6 for @ngtools/webpack, it works

so in package.json, replace
`"@ngtools/webpack": "^1.1.6",`
by
`"@ngtools/webpack": "1.1.6",`

i hope it will work on your side

**Comment by unsafecode** [comment] 2017-01-26 11:05
@alexmontdor @kyranjamie  Yeah, was investigating the same: we need to work very carefully with versioning, since SemVer is definitely not respected and it's very easy to incur in breaking changes.

Going to push fixes today.

**Comment by alexmontdor** [comment] 2017-01-27 17:06
I agree with you @unsafecode . We incounter lots of problem at the moment with webpack and angular 2.4.x and aot.. We have no clue how to solve it. Maybe it is worth posting on stackoverflow :)

Thanks to you both

**Comment by unsafecode** [comment] 2017-01-28 08:22
@alexmontdor I can confirm the issues you are describing. Luckly, I was able to make one configuration wok, in another project, by using:

`angular@2.4.5`
`@ngtools/webpack@1.2.3`
`webpack@2.2.0`

**and** by forcing the `tsconfig.aot.json` to include only module files, like:
```json
  "include": [
    "./src/app/app.module.ts",
    "./src/app/pages/*/index.ts",
    "./src/*.d.ts"
  ]
```

**Comment by alexmontdor** [comment] 2017-01-28 15:46
This extremely interessant this last comment. It would be a nice result after a week spend on this problem!
I'll try to make it work
If the lazy load is actually working then I'll share it on gitHub (and mentionned you) 

Thanks for sharing this info.

**Comment by tfsantosbr** [comment] 2017-03-15 13:13
same error here

**Comment by GeorgeKnap** [comment] 2017-04-04 06:57
I've got similar error trying this repo but there is a solution I found here: 
[https://github.com/angular/angular-cli/issues/5329](https://github.com/angular/angular-cli/issues/5329)

use this fix in your webpack.config.js 
```
let aotPlugin = new ngToolsWebpack.AotPlugin({
    tsConfigPath: './tsconfig.aot.json'
});
// workaround https://github.com/angular/angular-cli/issues/5329
aotPlugin._compilerHost._resolve = function (path_to_resolve) {
    path_1 = require("path");
    path_to_resolve = aotPlugin._compilerHost._normalizePath(path_to_resolve);
    if (path_to_resolve[0] == '.') {
        return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost.getCurrentDirectory(), path_to_resolve));
    }
    else if (path_to_resolve[0] == '/' || path_to_resolve.match(/^\w:\//)) {
        return path_to_resolve;
    }
    else {
        return aotPlugin._compilerHost._normalizePath(path_1.join(aotPlugin._compilerHost._basePath, path_to_resolve));
    }
};
```

**Comment by unsafecode** [comment] 2017-08-10 08:33
Should be fixed after merging the ng4 PR

**Closed as completed by unsafecode** 2017-08-10 08:33 UTC
